# Define Storage Class

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.175
  share: /srv/nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4

---

# Define Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: avida-pv-claim
  namespace: avida-experiments
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

# Define Job

apiVersion: batch/v1
kind: Job
metadata:
  name: avida-job
  namespace: avida-experiments
spec:
  completionMode: Indexed
  namespace: avida-experiments
  parallelism: 2
  completions: 2
  template:
    spec:
      volumes:
      - name: avida-pv-storage
        persistentVolumeClaim:
          claimName: avida-pv-claim
      containers:
      - name: avida
        image: raulya/avida:2.15
        resources:
          requests:
            memory: "200Mi"
            cpu: "600m"
          limits:
            memory: "300Mi"
            cpu: "800m"
        command:
        - /bin/bash
        - -exc
        - |
          cd /avida
          ./avida -set DATA_DIR data -set WORLD_X 100 -set WORLD_Y 100 -set COPY_MUT_PROB 0 -set DIVIDE_INS_PROB 0 -set DIVIDE_DEL_PROB 0 -set OFFSPRING_SIZE_RANGE 1 -set MIN_COPIED_LINES 0 -set MIN_EXE_LINES 0 -set REQUIRE_EXACT_COPY 1 -set STERILIZE_UNSTABLE 1 -set HARDWARE_TYPE 2 -set BASE_MERIT_METHOD 1 -set DEATH_METHOD 1 -set AGE_LIMIT 3000 -set MAX_CPU_THREADS 2 -set PARASITE_VIRULENCE 0.9 -set PARASITE_NO_COPY_MUT 1 -set INJECT_METHOD 1 -set REQUIRE_SINGLE_REACTION 1 -set DIVIDE_MUT_PROB 0.025 -set INJECT_MUT_PROB 0.01 -set VERBOSITY 0
          mkdir -p /data/$MY_POD_NAME
          cp -R /avida/data/* /data/$MY_POD_NAME
        volumeMounts:
        - mountPath: "/data"
          name: avida-pv-storage
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: Never
  backoffLimit: 4

