apiVersion: batch/v1
kind: Job
metadata:
  name: avida-job
spec:
  completionMode: Indexed
  parallelism: 3
  completions: 3
  template:
    spec:
      containers:
      - name: avida
        image: avida:local
        resources:
          requests:
            memory: "200Mi"
            cpu: "600m"
          limits:
            memory: "300Mi"
            cpu: "800m"
        command:
        - /bin/bash
        - -exc
        - |
          cd /avida
          ./run-avida.txt
      restartPolicy: Never
  backoffLimit: 4
